/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wuzl_jnitest_HelloWorldJNI */

#ifndef _Included_com_wuzl_jnitest_HelloWorldJNI
#define _Included_com_wuzl_jnitest_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wuzl_jnitest_HelloWorldJNI
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wuzl_jnitest_HelloWorldJNI_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_wuzl_jnitest_HelloWorldJNI
 * Method:    setString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wuzl_jnitest_HelloWorldJNI_setString
  (JNIEnv *, jobject, jstring);


#ifdef __cplusplus
}
#endif
#endif
